set hidden "Move between buffers without save
set noeol "Do not add automatic new line at the end of file
set incsearch
set hlsearch

" Microsoft WS definitions
set tabstop=4
set expandtab
set shiftwidth=2

" tell vim to keep a backup file
set backup

" tell vim where to put its backup files
set backupdir=~/tmp

" tell vim where to put swap files
set dir=~/tmp

